# Generated by Django 3.1.6 on 2021-04-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constructors',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ref', models.CharField(blank=True, max_length=250, null=True)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('nationality', models.CharField(blank=True, max_length=250, null=True)),
                ('url', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'constructors',
                'managed': False,
            },
        ),
    ]
